name: CI

on:
  push:
    branches:
      - master
      
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@e8d4307400f9427dba7cb98e488d6ab85f1cec5f

      - name: Build and start application
        run: docker compose up -d --build

      - name: Wait for application to become healthy
        run: |
          CONTAINER_ID=$(docker compose ps -q)

          until [ "$(docker inspect -f '{{.State.Health.Status}}' "$CONTAINER_ID")" = "healthy" ]; do
            sleep 2
          done
      
      - name: Show running containers
        run: docker compose ps

      - name: Smoke test
        run: curl --fail http://localhost

      - name: Verify page content
        run: |
          curl http://localhost | grep "DevOps Assistant"
        
      - name: Stop application
        if: always()
        run: docker compose down