name: Docker Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@e8d4307400f9427dba7cb98e488d6ab85f1cec5f

      - name: Start Application
        run: docker compose up -d --build

      